sudo apt-get update -y;
sudo apt-get upgrade -y;
sudo apt-get install -y feh;
cd ~;
wget -P ~/ https://github.com/Moomba42/custom-kiosks/archive/refs/heads/main.zip;
unzip main.zip;
rm main.zip;
cd custom-kiosks-main;
cd rpi-photo-display;
chmod 755 launcher.sh;
sudo reboot;
